var guarantee = require('./guaranteeTemplate');
var request = require('request');

/**
 * applyGuarantee
 * Use guarantee template (guaranteeTemplate.js) to apply new guarantee request
 * @param {String} token generated by getToken()
 * @returns {Object}
 */
function applyGuarantee(token) {
    const body = guarantee;
    guarantee.GuaranteeApplicationDetails.PartyReference.ApplicantReference = Date.now().toString()
    const options = {
        method: 'POST',
        url: 'https://api.apisure.io/mapi_base/v1/Guarantee/Guarantee/Apply',
        headers:
        {
            'Authorization': 'Bearer ' + token,
            'X-Apisure-Sender-ID': 'ImexConsumerBASE',
            'X-Apisure-Reciepent-ID': 'IMEXBase8',
        },
        body: guarantee,
        json: true
    };
    return new Promise((resolve, reject) => {
        request(options, function (error, response, body) {
            if (error) {
                reject(error);
            }

            resolve(body);
        });
    });
}

/**
 * getToken
 * Creates fresh authorization token (can be created once, not needed for each request)
 * @returns {String} fresh auth token
 */
function getToken() {
    const options = {
        method: 'POST',
        url: 'https://api.apisure.io/oauth/client_credential/accesstoken',
        qs: { grant_type: 'client_credentials' },
        headers:
        {
            Connection: 'keep-alive',
            'Content-Length': '73',
            'Accept-Encoding': 'gzip, deflate',
            Host: 'api.apisure.io',
            Accept: '*/*',
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        form:
        {
            client_id: 'APISURE_CLIENT_ID',
            client_secret: 'APISURE_CLIENT_SECRET'
        }
    };

    return new Promise((resolve, reject) => {
        request(options, function (error, response, body) {
            if (error) {
                reject(error);
            }
            resolve(JSON.parse(body).access_token);
        });
    });
}

getToken()
    .then((token) => {
        return applyGuarantee(token);
    }).then((apisureResponse) => {
        console.log(apisureResponse)
    }).catch((e) => {
        res.send(error)
    });